POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "ayeshaathoi162@gmail.com",
    "password": "1234"
}

###

GET http://localhost:3000/patient/doctorall

###
POST http://localhost:3000/patient/addreview/7
Content-Type:  application/json

{
    "complaint_text": "I am fine now",
    "rating": 4
}