POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "ayeshaathoi162@gmail.com",
    "password": "1234"
}

###

{
    "price": 900,
    "time" : "10:00 AM",
    "date" : "2021-02-02",
    "payment_method" : "Bkash",
    "payment_status" : "Paid",
    "patient_mobile" : "01700000000",
    "hospital_name" : "DMC",
    "test_names" : ["Blood Test","X-Ray"]
}
####
POST http://localhost:3000/booking/2/select/test
Content-Type: application/json

{
    "hospital_name" : "DMC",
    "test_names" : ["Blood Test","X-Ray"]
}
####

POST http://localhost:3000/booking/2/ambulance
Content-Type: application/json

{
    "price" : 1500,
    "time" : "10:00 AM",
    "date" : "2021-02-02",
    "payment_method" : "Bkash",
    "payment_status" : "Paid",
    "patient_mobile" : "01700000000",
    "driver_id" : 9,
    "hospital_name" : "DMC"
}


############
POST http://localhost:3000/doctor/addschedule/14
Content-Type: application/json

{
    "timeline" : [
    {
        "weekday": "Monday",
        "slot": 20,
        "start_time": "08:00:00",
        "end_time": "12:00:00",
        "hospital_name": "DMC"
    },
    {
        "weekday": "TUESDAY",
        "slot": 20,
        "start_time": "09:00:00",
        "end_time": "13:00:00"
    }
    
]
}
####

POST http://localhost:3000/doctor/addPrescription/2
Content-Type: application/json

{
    "disease": "Some disease",
    "tests": "Some tests",
    "suggestions": "Some suggestions",
    "medicine": "Some medicine"
}

##### 


#####view prescription
GET http://localhost:3000/doctor/viewprescription/10

#####

####check prescription
GET http://localhost:3000/doctor/checkprescription/15

####
#####
GET http://localhost:3000/doctor/profile/14
#####
POST  http://localhost:3000/doctor/update-profile/36
Content-Type: application/json

{
    "speciality": "Medicine Specialist",
    "designation": "Senior Consultant",
    "qualification": "MD,phD",
    "mobile_no": "01711223344"
}
#####
POST http://localhost:3000/comment/add/2
Content-Type: application/json

{
    "booking_id" : 1,
    "message" : "Hello"
}

####
POST http://localhost:3000/comment/get/2
Content-Type: application/json

{
    "booking_id" : 1
}
GET http://localhost:3000/patient/doctorall

###
POST http://localhost:3000/patient/addreview/7
Content-Type:  application/json

{
    "complaint_text": "I am fine now",
    "rating": 4
}