const DB_NAME = `"yourdoctor_db"`

module.exports = {
    //User Table
    TABLE_USER : `users`,
    TABLE_USER_ID: `uid`,
    TABLE_USER_USERNAME: `uname`,
    TABLE_USER_TYPE : `user_type`,
    TABLE_USER_EMAIL: `email`,
    TABLE_USER_PASSWORD: `pass`,
    TABLE_USER_MOBILE_NO: `mobile_no`,
    TABLE_USER_DOB: `dob`,
    TABLE_USER_GENDER : `gender`,
    //Hospital Table
    TABLE_HOSPITAL : `hospital`,
    TABLE_HOSPITAL_ID : `hospital_id`,
    TABLE_HOSPITAL_NAME : `hospital_name`,
    TABLE_HOSPITAL_VERIFICATION : `verification_status`,
    TABLE_HOSPITAL_EMAIL : `email`,
    TABLE_HOSPITAL_PASSWORD : `pass`,
    TABLE_HOSPITAL_MOBILE_NO : `mobile`,
    TABLE_HOSPITAL_STREET : `street`,
    TABLE_HOSPITAL_THANA : `thana`,
    TABLE_HOSPITAL_CITY : `city`,
    TABLE_HOSPITAL_DISTRICT : `district`,
    TABLE_HOSPITAL_DOCUMENT : `document`,
    TABLE_HOSPITAL_DOCUMENT_CONTENT : `document_status`,
    //Doctor Table
    TABLE_DOCTOR : `doctor`,
    TABLE_DOCTOR_ID : `doctor_id`,
    TABLE_DOCTOR_QUALIFICATION : `qualification`,
    TABLE_DOCTOR_DESIGNATION : `designation`,
    TABLE_DOCTOR_SPECIALITY : `speciality`,
    TABLE_DOCTOR_STATUS : `employee_status`,
    TABLE_DOCTOR_ZOOM_LINK : `zoom_link`,
    TABLE_DOCTOR_OLD_PATIENT_FEE : `old_patient_fee`,
    TABLE_DOCTOR_NEW_PATIENT_FEE : `new_patient_fee`,
    TABLE_DOCTOR_DOCUMENT : `document`,
    TABLE_DOCTOR_DOCUMENT_CONTENT : `document_content`,
    //doctor_hospital
    TABLE_DOCTOR_HOSPITAL : `doctor_hospital`,
    TABLE_DOCTOR_ID_HOSPITAL : `doctor_id`,
    TABLE_DOCTOR_HOSPITAL_ID : `hospital_id`,
    //Nurse Table
    TABLE_NURSE : `nurse`,
    TABLE_NURSE_ID : `nurse_id`,
    TABLE_NURSE_DESIGNATION : `designation`,
    TABLE_NURSE_STATUS : `employee_status`,
    TABLE_NURSE_DOCUMENT : `document`,
    TABLE_NURSE_DOCUMENT_CONTENT : `document_content`,
    TABLE_NURSE_HOSPITAL : `hospital_id`,
    //NURSE_TEST
    TABLE_TEST_NURSE_ID: `nurse_id`,
    TABLE_NURSE_TEST_ID : `test_id`,
    //Driver Table
    TABLE_DRIVER : `driver`,
    TABLE_DRIVER_ID : `driver_id`,
    TABLE_DRIVER_AMBULANCE_TYPE : `ambulance_type`,
    TABLE_DRIVER_AMBULANCE_FARE : `ambulance_fare`,
    TABLE_DRIVER_STREET : `street`,
    TABLE_DRIVER_THANA : `thana`,
    TABLE_DRIVER_CITY : `city`,
    TABLE_DRIVER_DISTRICT : `district`,
    TABLE_DRIVER_DOCUMENT : `document`,
    TABLE_DRIVER_DOCUMENT_CONTENT : `document_content`,
    TABLE_DRIVER_STATUS : `employee_status`,
    TABLE_DRIVER_HOSPITAL : `hospital_id`,
    //Patient Table
    TABLE_PATIENT : `patient`,
    TABLE_PATIENT_ID : `pid`,
    TABLE_PATIENT_STREET : `street`,
    TABLE_PATIENT_THANA : `thana`,
    TABLE_PATIENT_CITY : `city`,
    TABLE_PATIENT_DISTRICT : `district`,
    //Test Table
    TABLE_TEST    : `test`,
    TABLE_TEST_ID : `testid`,
    TABLE_TEST_NAME : `testname`,
    TABLE_TEST_PRICE : `price`,
    TABLE_TEST_HOSPITAL_ID : `hospital_id`,
    //BOOKING TEST
    TABLE_BOOKING_TEST : `Booking_TESTS`,
    TABLE_BOOKING_TEST_ID : `test_id`,
    //Doctor_TimeLine
    TABLE_DOCTOR_TIMELINE : `timeline`,
    TABLE_DOCTOR_TIMELINE_ID : `timeline_id`,
    TABLE_DOCTOR_TIMELINE_WEEKDAY : `weekday`,
    TABLE_DOCTOR_TIMELINE_SLOT : `slot`,
    TABLE_TIMELINE_MEETING_TYPE : `meeting_type`,
    TABLE_DOCTOR_TIMELINE_START_TIME : `start_time`,
    TABLE_DOCTOR_TIMELINE_END_TIME : `end_time`,
    TABLE_DOCTOR_TIMELINE_DOCTOR_ID : `doctor_id`,
    TABLE_DOCTOR_TIMELINE_HOSPITAL_ID : `hospital_id`,
    //Booking Table
    TABLE_BOOKING  : `booking`,
    TABLE_BOOKING_ID : `booking_id`,
    TABLE_BOOKING_TYPE : `type`,
    TABLE_BOOKING_TOTAL_PRICE : `total_price`,
    TABLE_BOOKING_DATE : `date`,
    TABLE_BOOKING_TIME : `time`,
    TABLE_BOOKING_PAYMENT_METHOD : `payment_method`,
    TABLE_BOOKING_PAYMENT_STATUS : `payment_status`,
    TABLE_BOOKING_PATIENT_MOBILE : `patient_mobile`,
    TABLE_BOOKING_STATUS : `booking_status`,
    TABLE_BOOKING_SERIAL : `appointment_serial`,
    TABLE_BOOKING_PATIENT_ID : `patient_id`,
    TABLE_BOOKING_DOCTOR_ID : `doctor_id`,
    TABLE_BOOKING_NURSE_ID : `nurse_id`,
    TABLE_BOOKING_DRIVER_ID : `driver_id`,  
    TABLE_BOOKING_HOSPITAL_ID : `hospital_id`,
    //review table
    TABLE_REVIEWS : `review`,
    TABLE_REVIEWS_RATING : `rating`,
    TABLE_REVIEWS_COMPLAINT_TEXT : `complaint_text`,
    TABLE_REVIEWS_BOOKING_ID : `booking_id`,
    //Ambulance
    TABLE_AMBULANCE : `ambulance`,
    TABLE_AMBULANCE_ID : `ambulance_id`,
    TABLE_AMBULANCE_TYPE : `ambulance_type`,
    TABLE_AMBULANCE_FARE : `ambulance_fare`,
    TABLE_AMBULANCE_HOSPITAL_ID : `hospital_id`,
    TABLE_AMBULANCE_DRIVER_ID : `driver_id`,
    //CHAT Message
    TABLE_CHAT_MESSAGE : `Chat_message`,
    TABLE_CHAT_MESSAGE_ID : `msg_id`,
    TABLE_CHAT_MESSAGE_BOOKING_ID : `booking_id`,
    TABLE_CHAT_MESSAGE_SENDER_ID : `sender_id`,
    TABLE_CHAT_MESSAGE_MESSAGE : `message`,
    TABLE_CHAT_MESSAGE_TIMESTAMP : `timestamp`,
    //Prescription
    TABLE_PRESCRIPTION : `prescription`,
    TABLE_PRESCRIPTION_ID : `prescription_id`,
    TABLE_PRESCRIPTION_PDF : 'prescription_pdf',
    TABLE_PRESCRIPTION_DATE : 'prescription_date',
    TABLE_PRESCRIPTION_DOCTOR_ID : 'doctor_id',
    TABLE_PRESCRIPTION_PATIENT_ID : 'pid',

}