const DB_NAME = `"yourdoctor_db"`

module.exports = {
    //User Table
    TABLE_USER : `users`,
    TABLE_USER_ID: `uid`,
    TABLE_USER_USERNAME: `uname`,
    TABLE_USER_EMAIL: `email`,
    TABLE_USER_PASSWORD: `pass`,
    TABLE_USER_MOBILE_NO: `mobile_no`,
    TABLE_USER_DOB: `dob`,
    TABLE_USER_GENDER : `gender`,
    //Hospital Table
    TABLE_HOSPITAL : `hospital`,
    TABLE_HOSPITAL_ID : `hospital_id`,
    TABLE_HOSPITAL_NAME : `hospital_name`,
    TABLE_HOSPITAL_EMAIL : `email`,
    TABLE_HOSPITAL_PASSWORD : `pass`,
    TABLE_HOSPITAL_MOBILE_NO : `mobile`,
    TABLE_HOSPITAL_STREET : `street`,
    TABLE_HOSPITAL_THANA : `thana`,
    TABLE_HOSPITAL_CITY : `city`,
    TABLE_HOSPITAL_DISTRICT : `district`,
    //Doctor Table
    TABLE_DOCTOR : `doctor`,
    TABLE_DOCTOR_ID : `doctor_id`,
    TABLE_DOCTOR_DESIGNATION : `designation`,
    TABLE_DOCTOR_SPECIALITY : `speciality`,
    TABLE_DOCTOR_STATUS : `status`,
    TABLE_DOCTOR_DOCUMENT : `document`,
    //doctor_hospital
    TABLE_DOCTOR_HOSPITAL : `doctor_hospital`,
    TABLE_DOCTOR_ID_HOSPITAL : `doctor_id`,
    TABLE_DOCTOR_HOSPITAL_ID : `hospital_id`,
    //Nurse Table
    TABLE_NURSE : `nurse`,
    TABLE_NURSE_ID : `nurse_id`,
    TABLE_NURSE_DESIGNATION : `designation`,
    TABLE_NURSE_STATUS : `status`,
    TABLE_NURSE_DOCUMENT : `document`,
    TABLE_NURSE_HOSPITAL : `hospital_id`,
    //NURSE_TEST
    TABLE_TEST_NURSE_ID: `nurse_id`,
    TABLE_NURSE_TEST_ID : `test_id`,
    //Driver Table
    TABLE_DRIVER : `driver`,
    TABLE_DRIVER_ID : `driver_id`,
    TABLE_DRIVER_AMBULANCE_TYPE : `ambulance_type`,
    TABLE_DRIVER_STATUS : `status`,
    TABLE_DRIVER_DOCUMENT : `document`,
    TABLE_DRIVER_HOSPITAL : `hospital_id`,
    //Patient Table
    TABLE_PATIENT : `patient`,
    TABLE_PATIENT_ID : `pid`,
    TABLE_PATIENT_STREET : `street`,
    TABLE_PATIENT_THANA : `thana`,
    TABLE_PATIENT_CITY : `city`,
    TABLE_PATIENT_DISTRICT : `district`,
    //Test Table
    TABLE_TEST_ID : `testID`,
    TABLE_TEST_NAME : `testname`,
    TABLE_TEST_PRICE : `price`,
    TABLE_TEST_HOSPITAL_ID : `hospital_id`,
    //Doctor_TimeLine
    TABLE_DOCTOR_TIMELINE : `timeline`,
    TABLE_DOCTOR_TIMELINE_ID : `timeline_id`,
    TABLE_DOCTOR_TIMELINE_WEEKDAY : `weekday`,
    TABLE_DOCTOR_TIMELINE_SLOT : `slot`,
    TABLE_DOCTOR_TIMELINE_START_TIME : `start_time`,
    TABLE_DOCTOR_TIMELINE_END_TIME : `end_time`,
    TABLE_DOCTOR_TIMELINE_OLD_PATIENT_FEE : `old_patient_fee`,
    TABLE_DOCTOR_TIMELINE_NEW_PATIENT_FEE : `new_patient_fee`,
    TABLE_DOCTOR_TIMELINE_DOCTOR_ID : `doctor_id`,
    TABLE_DOCTOR_TIMELINE_HOSPITAL_ID : `hospital_id`,
    //Appointment 
    TABLE_APPOINTMENT  : `appointment`,
    TABLE_APPOINTMENT_ID : `appoint_id`,
    TABLE_APPOINTMENT_TYPE : `type`,
    TABLE_APPOINTMENT_TIME : `time`,
    TABLE_APPOINTMENT_STATUS : `status`,
    TABLE_APPOINTMENT_SERIAL : `serial`,
    TABLE_APPOINTMENT_RATING : `rating`,
    TABLE_APPOINTMENT_COMPLAINT_TEXT : `complaint_text`,
    TABLE_APPOINTMENT_PATIENT_ID : `patient_id`,
    TABLE_APPOINTMENT_DOCTOR_ID : `doctor_id`,
    TABLE_APPOINTMENT_NURSE_ID : `nurse_id`,
    TABLE_APPOINTMENT_DRIVER_ID : `driver_id`,  
}